pipeline {
 agent any
 tools {
  maven 'apache-maven-3.8.6'
 }

    stages {
        stage('Build') {
            steps {
               echo 'Building...'
            }
        }
        stage('Snyk OpenSource Test') {
         steps{
         echo "Testing..."
         snykSecurity(
                    snykInstallation: 'snyk@latest',
                    snykTokenId: 'organisation-snyk-api-token',
                    additionalArguments: '--all-projects --code',
                    failOnIssues: false
          
                )
         }   
        }
        stage('Snyk Code Test') {
         steps {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                sh 'snyk code test --sarif-file-output=results-code.sarif'
            }
            recordIssues  tool: sarif(name: 'Snyk Code', id: 'snyk-code', pattern: 'results-code.sarif')
         }
        }
    }
}
