pipeline {
 agent any
 tools {
  maven 'apache-maven-3.8.6',
  nodejs 'NodeJS 18.4.0'
 }

    stages {
        stage('Build') {
            steps {
               echo 'Building...'
            }
        }

       //Install the Snyk CLI with npm. For more information, check:
       // https://docs.snyk.io/snyk-cli/install-the-snyk-cli
        stage('Install snyk CLI') {
            steps {
                script {
                    sh 'npm install -g snyk'
                }
            }
        }

     // Authorize the Snyk CLI
        stage('Authorize Snyk CLI') {
            steps {
                withCredentials([string(snykTokenId: 'organisation-snyk-api-token', variable: 'organisation-snyk-api-token')]) {
                    sh 'snyk auth ${organisation-snyk-api-token}'
                }
            }
        }

     //Open Source Scan
        stage('Snyk OpenSource Test') {
         steps{
         echo "Testing..."
         snykSecurity(
                    snykInstallation: 'snyk@latest',
                    snykTokenId: 'organisation-snyk-api-token',
                    additionalArguments: '--all-projects --code',
                    failOnIssues: false
          
                )
         }   
        }
        stage('Snyk Code Test') {
         steps {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                sh 'snyk code test --sarif-file-output=results-code.sarif'
            }
            recordIssues  tool: sarif(name: 'Snyk Code', id: 'snyk-code', pattern: 'results-code.sarif')
         }
        }
    }
}
